# Exploring a Dataset through Its Metadata

Thursday Sept. 22, 2022

This is sneak preview of what we'll be using Jupyter notebooks to do in this course. For now, look at the code cells below. These Python commands will let you explore the Knoedler Art dataset that we explored in Exercise #2. 

NOTE: the first cell must be run before you can reun the others.

Click on the box below and then click on the (►), the "Run" icon, in the menu above:

In [2]:
# The command below imports the statistical library we'll be working with
import pandas as pd
# The command below tells our notebook the filepath to the dataset we'll be working with,
# and reads it in in a format that Python can interact with
knoedler_data = pd.read_csv("../_datasets/knoedler-art-auction-dataset/nyc_knoedler.csv")
pd.options.display.max_rows = 100
knoedler_data.head(10)

,title,artists,artist_nationality,genre,object_type,height,width,area,seller,seller_type,buyer,buyer_type,buyer_address,coordinates,purchase_date,sale_date,purchase_price,sale_price,sale_year,purchase_year
0,John Campbell,"RAEBURN, HENRY",British,Portrait,Painting,30.00,25.000,750.00000,Agnew's,Dealer,"Frick, Henry Clay",Collector,"1 E. 70th St., New York, NY, USA","40.771147,-73.967993",12/8/12,12/12/16,440.0,9500.0,1916,1912
1,Port of Adam Rolland of Gask Advocate Born 173...,"RAEBURN, HENRY",British,Portrait,Painting,35.75,27.625,987.59375,Wallis and Son,Dealer,"Jennings, Walter",Collector,"26 Broadway, New York, NY, USA","40.706214,-74.012948",1/13/12,5/2/12,725.0,8500.0,1912,1912
2,A pink on shore at Schweningen,"MARIS, JACOB HENRICUS",Dutch,Landscape,Painting,NaN,NaN,NaN,American Art Association,Dealer,"Lewisohn, Adolph",Collector,"9 W. 57th St., New York, NY, USA","40.763142,-73.974131",2/2/12,1/11/13,3400.0,4500.0,1913,1912
3,The Thau,"CAZIN, JEAN CHARLES",French,Landscape,Painting,NaN,NaN,NaN,American Art Association,Dealer,"Lewisohn, Adolph",Collector,"9 W. 57th St., New York, NY, USA","40.763142,-73.974131",2/2/12,2/3/12,1450.0,2250.0,1912,1912
4,"""No man's land"" [title from sales book 9, 1907...","WYANT, ALEXANDER HELWIG",American,Genre,Painting,NaN,NaN,NaN,American Art Association,Dealer,"Clark, William (New York)",Collector,"51 E. 74th St., New York, NY, USA","40.772964,-73.964079",2/2/12,2/8/12,6500.0,7500.0,1912,1912
5,Duke of Gloucester; H.R.H. Duke of Gloucester ...,"BEECHEY, WILLIAM",British,Portrait,Painting,NaN,NaN,NaN,"Reid, Daniel Gray",Collector,"Skinner, William Cobbett",Collector,"36 E. 39th St., New York, NY, USA","40.750728,-73.980512",2/2/12,3/1/13,1275.0,7500.0,1913,1912
6,"[""Banks of the river Oise at Conflans"" title i...","DAUBIGNY, CHARLES FRANÇOIS",French,Landscape,Painting,NaN,NaN,NaN,"Reid, Daniel Gray",Collector,"Gary, Elbert Henry",Collector,"Waldorf Astoria, New York, NY, USA","40.730079,-73.992841",2/2/12,5/6/12,12000.0,22000.0,1912,1912
7,Mrs. Alex Henderson From Coll of Mrs. J.M. Bur...,"RAEBURN, HENRY",British,Portrait,Painting,NaN,NaN,NaN,Colnaghi's,Dealer,"Milton, Mildred Anna",Collector,"46 E. 50th St., New York, NY, USA","40.757634,-73.975341",3/3/12,5/8/12,840.0,12000.0,1912,1912
8,Billy & Dick sellers; The Old Road Rolleboise ...,"RUSSEAU, PERCIVAL LEONARD",American,Landscape; Animals,Painting,NaN,NaN,NaN,"Russeau, Percival Leonard",Artist,"Borden, L.M.",Collector,"384 Fifth Ave., New York, NY, USA","40.76457,-73.973636",3/4/12,6/7/17,400.0,500.0,1917,1912
9,Matinée près Estrelles,"HARPIGNIES, HENRI",French,Landscape,Painting,32.00,25.750,824.00000,"Roebling, Charles G.",Collector,"Tanenbaum, Moses",Collector,"31 W. 75th St., New York, NY, USA","40.778599,-73.975293",3/12/12,4/4/12,4000.0,6000.0,1912,1912

### What sort of metadata is in this dataset? 
In order to answer this questions, we'll have to figure out what these fields mean
Lucky for us, this dataset comes with a contextual note!

In [16]:
from IPython.display import Markdown, display

display(Markdown("../_datasets/knoedler-art-auction-dataset/contextual-note.md"))

# Contextual Note for NYC Knoedler Dataset

This data comes from Mathew Lincoln's discussion of the dataset used in his "[Critical Data Visualization with Palladio"](https://matthewlincoln.net/mapping-knoedler-palladio/#introduction-to-the-workshop-data0) tutorial.

Dataset downloaded from GitHub in January 2021

This folder includes CSV Lincoln generated from a larger dataset created by staff at the Getty working on the [Getty Provenance Index](https://www.getty.edu/research/tools/provenance/search.html) (a database of metadata about art sales and ownership).

From Lincoln's description in the "Critical Data Visualization with Palladio" tutorial:

> " These data describe a little over 4,100 sales by the fine art dealer M. Knoedler & Co. between roughly 1870-1970, as documented in data encoded from the handwritten stockbooks by staff at the Getty Provenance Index. These stockbooks were where Knoedler recorded details about the artworks that entered their inventory, when and where they bought them from and for how much, and (if sold) who the eventual buyer was."

> The data in nyc_knoedler.csv covers only those cases in which:
> > 1. The transactions were actually recorded in the Knoedler stockbooks (they didn’t always keep good records!)
> > 2. The records contain original purchase and sale dates and prices.
> > 3. We have been able to identify both the buyer and the seller.
> > 4.  The buyer has a known street address located in Manhattan or Brooklyn (i.e. if our only location info says “New York, NY”, it is not included in this subset because it doesn’t contain street-level precision."


## Data dictionary (by Matthew Lincoln)


| field                | description                                                                                                                                                                                                                                                                                 |
| -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `title`              | Title of the work (if recorded)                                                                                                                                                                                                                                                             |
| `artists`            | Creator(s) of the artwork (if recorded. GPI edtiors recorded the original spelling as written by Knoedler, but also recorded a standardized version if they could identify the artist [e.g. turning "J. Sargent" into "SARGENT, JOHN SINGER"]. This field holds the standardized versions.) |
| `artist_nationality` | Creator(s) nationalities (input by modern editors)                                                                                                                                                                                                                                          |
| `genre`              | Genre of the work (input by modern editors)                                                                                                                                                                                                                                                 |
| `object_type`        | e.g. `Painting`, `Drawing`, `Sculpture` (input by modern editors)                                                                                                                                                                                                                           |
| `height`             | Height in inches (if recorded)                                                                                                                                                                                                                                                              |
| `width`              | Width in inches (if recorded)                                                                                                                                                                                                                                                               |
| `area`               | Area in square inches (if recorded)                                                                                                                                                                                                                                                         |
| `seller`             | Name of seller (Standardized in a similar manner to the artists. Numeric ID if anonymous/unknown)                                                                                                                                                                                           |
| `seller_type`        | e.g. `Dealer`, `Museum`, `Artist`, `Collector`                                                                                                                                                                                                                                              |
| `buyer`              | Name of buyer (Standardized in a similar manner to the artists. Numeric ID if anonymous/unknown)                                                                                                                                                                                            |
| `buyer_type`         | e.g. `Dealer`, `Museum`, `Artist`, `Collector`                                                                                                                                                                                                                                              |
| `buyer_address`      | Buyer address                                                                                                                                                                                                                                                                               |
| `coordinates`        | Coordinates in the format `lat,lon`                                                                                                                                                                                                                                                         |
| `purchase_date`      | Date object brought into Knoedler stock in the format `YYYY-MM-DD`                                                                                                                                                                                                                          |
| `sale_date`          | Date object sold out of Knoedler stock in the format `YYYY-MM-DD`                                                                                                                                                                                                                           |
| `purchase_price`     | Price Knoedler paid to buy the object (normalized to 1900 USD)                                                                                                                                                                                                                              |
| `sale_price`         | Price Knoedler received for selling the object (normalized to 1900 USD)                                                                                                                                                                                                                     |

---

### Taking stock 

Look at the categories in our data dictionary and in the dataset. 

1. What kind of data is captured in this dataset about artwork sales? 
2. What kinds of questions might we ask about it?
3. Anything stand out as particularly noteworthy?

### Using metadata to count 
Right now we have a mix of qualitative data (things like what genre a particular artwork sold was classified as) as well as quantitative data (sale price, sale year, etc). Some of this data is recorded using what's called a "controlled" vocabulary, meaning that it is recorded in a standardized form. Some of these include names (recorded in a standardize manner) and categories like "genre." (For more background on this, see the full Knoedler Stockbooks data dictionary here: https://github.com/thegetty/provenance-index-csv/tree/main/knoedler#data-dictionary

Metadata is useful! It helps us to look at patterns in the larger dataset

What if we want to know the frequence of certain data categories, like different types of art objects in the dataset, the different nationalities of the artists sold by Knoedler, or the top 20 buyers represented in the dataset?  Click on any ofthe 3 cells below, then click (►).

In [ ]:
#Show the types of art objects, in order of frequency
knoedler_data["object_type"].value_counts()

In [ ]:
#Show the artist nationalities, in order of frequency
knoedler_data["artist_nationality"].value_counts()

In [ ]:
#Show the top 20 buyers of art from Knoedler
knoedler_data["buyer"].value_counts()[:20]

What if we wanted to look at at the frequencies of a different cateogry, like the genres?
Copy the text in the cell above, and change `object-type` to `genre`, then run the cell.

### Using metadata to filter our dataset

What if we want to use the "genre" category to look for only paintings that were classified as "Animals"? Click on the cell below, then click (►).

In [3]:
knoedler_data[knoedler_data["genre"] == "Animals"]

,title,artists,artist_nationality,genre,object_type,height,width,area,seller,seller_type,buyer,buyer_type,buyer_address,coordinates,purchase_date,sale_date,purchase_price,sale_price,sale_year,purchase_year
21,Turtle,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,"Mallet, Ernst",Dealer,"Henschel, Charles R.",Collector,"22 E. 47th St., New York, NY, USA","40.756873,-73.979111",6/12/12,4/10/17,2777.777778,30.0,1917,1912
38,Lion walking,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,Roebel and Reinhardt Galleries,Dealer,"Sheffield, James Rockwell, Mrs.",Collector,"45 E. 67th St., New York, NY, USA","40.76838,-73.967527",10/5/12,12/9/20,5000.000000,1137.5,1920,1912
39,Tiger walking,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,Roebel and Reinhardt Galleries,Dealer,"Sheffield, James Rockwell, Mrs.",Collector,"45 E. 67th St., New York, NY, USA","40.76838,-73.967527",10/2/12,12/4/20,5000.000000,1137.5,1920,1912
47,Cattle,"VOLTZ, FRIEDRICH",German,Animals,Painting,NaN,NaN,NaN,"Fleischmann, E.A. Fine Art Gallery",Dealer,"Myers, Julien L.",Collector,"5 W. 53rd St., New York, NY, USA","40.760522,-73.975865",1878-10-10,1879-12-12,3114.000000,900.0,1879,1878
52,Lion with lifted Paw,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,"Messmore, Carman Harriot",Collector,"Heckscher, August",Collector,"320 Park Ave., New York, NY, USA","40.757458,-73.973914",11/4/12,1/3/17,300.000000,300.0,1917,1912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4180,Panther at the spring,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,"Mallet, Ernst",Dealer,"Scholle, Albert W.",Collector,"763 Fifth Ave., New York, NY, USA","40.764208,-73.973922",12/12/11,2/9/12,4000.000000,2500.0,1912,1911
4181,Jaguar sleeping,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,"Mallet, Ernst",Dealer,"Scholle, Albert W.",Collector,"763 Fifth Ave., New York, NY, USA","40.764208,-73.973922",12/12/11,12/2/12,3500.000000,2500.0,1912,1911
4182,Eagle on a rock,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,"Mallet, Ernst",Dealer,"Winthrop, Grenville Lindall",Collector,"27 E. 37th St., New York, NY, USA","40.749575,-73.98156",12/12/11,4/1/12,3500.000000,1600.0,1912,1911
4186,Bear Playing,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,Obach and Company,Dealer,"Redmond, Roland L.",Collector,"31 E. 72nd St., New York, NY, USA","40.771781,-73.965435",7/7/11,1/11/21,65.000000,650.0,1921,1911
4187,Jaguar & Gavial,"BARYE, ANTOINE LOUIS",French,Animals,Sculpture,NaN,NaN,NaN,Obach and Company,Dealer,"Holmes, Myron",Collector,"36 E. 49th St., New York, NY, USA","40.758523,-73.979223",7/7/11,10/4/15,45.000000,350.0,1915,1911

## Using Metadata to get a sense of the dataset itself

Metadtaa can tell us a lot! Importantly, it can tell us not just the things that the dataset describes, but what's going on in the dataset itself. 

**Question: We know this is data from Knoedler auctions between 1870-1970, but how much coverage does this dataset actually have?**

Let's take a look at those coordinates. Click on the cell below, then click (►).

In [ ]:
knoedler_data["sale_year"].value_counts(sort=False)

Let's try to plot this data to get a better sense of it.Click on the cell below, and then click (►).

In [ ]:
knoedler_data["sale_year"].value_counts(sort=False).plot(kind='bar', figsize=(25,8), rot=45)

What do you notice about the patterns in sale? What can we say about those gaps––knowing what we know about the dataset?